### ISSUE TITLE
set the input submit to disabled if state.loading = true

### ISSUE THREAD

**Issue by ilyes-kechidi** [aladin002dz/GetMovieData#1]
https://github.com/aladin002dz/GetMovieData/blob/177cd8f24c42f975a3499bac33c0f8cf7c2bc360/src/components/MovieFinder.js#L111

**Comment by aladin002dz** [comment]
very subtle remark, I'll handle it! :)

**Comment by aladin002dz** [comment]
Handled, thanks for the feedback Ilyes <3 :
              <input
				...
                disabled = {(loading )? "disabled" : ""}
                />
